<a href="https://colab.research.google.com/github/tuychiyevkm/Pandas-start/blob/main/Pandas_DF_Series_hw_nt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
u = files.upload()
for i in u.keys():
  print('The file "{name}" has been uploaded:{lenght} b'.format(name = i, lenght = len(u[i])))

Saving Student_data.csv to Student_data.csv
The file "Student_data.csv" has been uploaded:274402 b

In [ ]:
from google.colab import files
u = files.upload()
for i in u.keys():
  print('The file "{name}" has been uploaded:{lenght} b'.format(name = i, lenght = len(u[i])))

Saving itunes_music_dataset.csv to itunes_music_dataset.csv
The file "itunes_music_dataset.csv" has been uploaded:2155178 b

In [ ]:
df1 = pd.read_csv("Student_data.csv")
df1

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
0,ID00001,Male,20,Engineering,83.9,4.4,2.65,9.1,8,2.78
1,ID00002,Female,24,Business,80.7,4.0,3.58,4.0,4,3.76
2,ID00003,Female,20,Mathematics,91.5,3.9,3.29,6.7,4,3.75
3,ID00004,Female,23,Engineering,73.9,8.8,3.48,4.0,6,3.69
4,ID00005,Male,21,Economics,79.8,2.2,2.66,8.7,6,2.34
...,...,...,...,...,...,...,...,...,...,...
4995,ID04996,Female,23,Mathematics,83.9,2.4,3.21,7.5,8,3.31
4996,ID04997,Male,20,Economics,82.8,7.2,3.12,7.6,7,3.70
4997,ID04998,Male,19,Engineering,92.2,13.5,3.55,6.3,6,4.00
4998,ID04999,Female,22,Computer Science,100.0,2.4,2.86,7.0,6,2.93
4999,ID05000,Female,20,Mathematics,86.5,7.4,2.49,7.8,4,3.07

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           5000 non-null   object
 1   Gender               5000 non-null   object
 2   Age                  5000 non-null   int64
 3   Major                5000 non-null   object
 4   Attendance_Pct       5000 non-null   float64
 5   Study_Hours_Per_Day  5000 non-null   float64
 6   Previous_GPA         5000 non-null   float64
 7   Sleep_Hours          5000 non-null   float64
 8   Social_Hours_Week    5000 non-null   int64
 9   Final_CGPA           5000 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 390.8+ KB

In [ ]:
d = df1.describe()
print(d)

               Age  Attendance_Pct  Study_Hours_Per_Day  Previous_GPA  \
count  5000.000000     5000.000000          5000.000000   5000.000000
mean     20.948600       83.795740             4.517840      3.093824
std       2.017417       12.867904             2.568104      0.476754
min      18.000000       26.200000             0.100000      1.350000
25%      19.000000       75.100000             2.600000      2.760000
50%      21.000000       85.050000             4.000000      3.100000
75%      23.000000       94.800000             6.000000      3.430000
max      24.000000      100.000000            14.000000      4.000000

       Sleep_Hours  Social_Hours_Week   Final_CGPA
count  5000.000000        5000.000000  5000.000000
mean      7.012060           8.006400     3.272224
std       1.424377           2.797771     0.507954
min       4.000000           0.000000     1.160000
25%       6.000000           6.000000     2.920000
50%       7.000000           8.000000     3.310000
75%       8.000000          10.000000     3.680000
max      10.000000          20.000000     4.000000

In [ ]:
df1.head(7)

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
0,ID00001,Male,20,Engineering,83.9,4.4,2.65,9.1,8,2.78
1,ID00002,Female,24,Business,80.7,4.0,3.58,4.0,4,3.76
2,ID00003,Female,20,Mathematics,91.5,3.9,3.29,6.7,4,3.75
3,ID00004,Female,23,Engineering,73.9,8.8,3.48,4.0,6,3.69
4,ID00005,Male,21,Economics,79.8,2.2,2.66,8.7,6,2.34
5,ID00006,Male,20,Business,86.8,3.5,2.16,7.0,7,2.41
6,ID00007,Male,22,Mathematics,77.5,3.6,2.66,8.7,5,2.69

In [ ]:
df1.tail(6)

,Student_ID,Gender,Age,Major,Attendance_Pct,Study_Hours_Per_Day,Previous_GPA,Sleep_Hours,Social_Hours_Week,Final_CGPA
4994,ID04995,Male,18,Economics,98.5,3.8,2.88,5.8,7,3.11
4995,ID04996,Female,23,Mathematics,83.9,2.4,3.21,7.5,8,3.31
4996,ID04997,Male,20,Economics,82.8,7.2,3.12,7.6,7,3.70
4997,ID04998,Male,19,Engineering,92.2,13.5,3.55,6.3,6,4.00
4998,ID04999,Female,22,Computer Science,100.0,2.4,2.86,7.0,6,2.93
4999,ID05000,Female,20,Mathematics,86.5,7.4,2.49,7.8,4,3.07

In [ ]:
newdf = pd.DataFrame({
    'Student_ID': ['ID05001'],
    'Gender': ['Male'],
    'Age': ['22'],
    'Major': ['Computer Science'],
    'Attendance_Pct': [91.1],
    'Study_Hours_Per_Day': [9],
    'Previous_GPA': [3.55],
    'Sleep_Hours' : [7],
    'Social_Hours_Week' : [2],
    'Final_CGPA' : [3.7]
})
con_new = pd.concat([df1, newdf], ignore_index=True)
print(con_new)

     Student_ID  Gender Age             Major  Attendance_Pct  \
0       ID00001    Male  20       Engineering            83.9
1       ID00002  Female  24          Business            80.7
2       ID00003  Female  20       Mathematics            91.5
3       ID00004  Female  23       Engineering            73.9
4       ID00005    Male  21         Economics            79.8
...         ...     ...  ..               ...             ...
4996    ID04997    Male  20         Economics            82.8
4997    ID04998    Male  19       Engineering            92.2
4998    ID04999  Female  22  Computer Science           100.0
4999    ID05000  Female  20       Mathematics            86.5
5000    ID05001    Male  22  Computer Science            91.1

      Study_Hours_Per_Day  Previous_GPA  Sleep_Hours  Social_Hours_Week  \
0                     4.4          2.65          9.1                  8
1                     4.0          3.58          4.0                  4
2                     3.9          3.29          6.7                  4
3                     8.8          3.48          4.0                  6
4                     2.2          2.66          8.7                  6
...                   ...           ...          ...                ...
4996                  7.2          3.12          7.6                  7
4997                 13.5          3.55          6.3                  6
4998                  2.4          2.86          7.0                  6
4999                  7.4          2.49          7.8                  4
5000                  9.0          3.55          7.0                  2

      Final_CGPA
0           2.78
1           3.76
2           3.75
3           3.69
4           2.34
...          ...
4996        3.70
4997        4.00
4998        2.93
4999        3.07
5000        3.70

[5001 rows x 10 columns]

In [ ]:
df2 = pd.read_csv("itunes_music_dataset.csv")
df2

,track_id,track_name,artist_name,collection_name,album_artist,genre,rating,track_price,collection_price,release_date,track_time_millis,country,currency,preview_url,artwork_url
0,1624932774,POP!,NAYEON,IM NAYEON,NaN,Dance,Clean,1.29,6.99,2022-06-24T12:00:00Z,168107,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
1,1022164261,Riptide,Vance Joy,Dream Your Life Away (Special Edition),NaN,Alternative,Clean,1.29,9.99,2013-03-22T07:00:00Z,202019,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
2,1207120448,Something Just Like This,The Chainsmokers & Coldplay,Memories...Do Not Open,The Chainsmokers,Dance,Clean,1.29,9.99,2017-02-22T08:00:00Z,247165,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
3,1369380479,lovely,Billie Eilish & Khalid,lovely - Single,NaN,Pop,Clean,1.29,1.29,2018-04-19T12:00:00Z,200187,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4,1450695872,when the party's over,Billie Eilish,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",NaN,Alternative,Clean,1.29,10.99,2018-10-17T07:00:00Z,196077,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4910,712330693,I Got 5 On It (feat. Michael Marshall),Luniz,Operation Stackola,NaN,Hip-Hop/Rap,Clean,1.29,7.99,1995-05-23T07:00:00Z,253533,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4911,1817490073,Dekh Lo Awaz Dekar (Prem Geet / Soundtrack Ver...,Anuradha Paudwal,Old Hindi Songs - Vol.2,Kishore Kumar & Asha Bhosle,Soundtrack,Clean,NaN,NaN,1981-01-01T12:00:00Z,355067,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4912,1817490077,Khwabon Ko (Prem Geet / Soundtrack Version),Suresh Wadkar,Old Hindi Songs - Vol.2,Kishore Kumar & Asha Bhosle,Soundtrack,Clean,NaN,NaN,1981-01-01T12:00:00Z,232027,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4913,1817490076,"Suhani Sham Aayi Hai (From ""Shaukeeen"")",Asha Bhosle & R.D. Burman,Old Hindi Songs - Vol.2,Kishore Kumar & Asha Bhosle,Soundtrack,Clean,NaN,NaN,1982-01-01T12:00:00Z,283403,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...
4914,1817507850,"Mujhe Tadpati Rahi (From ""Damaad"")",Asha Bhosle & Mohd. Rafi,Old Hindi Songs - Vol.1,Kishore Kumar,Soundtrack,Clean,NaN,NaN,2007-05-07T12:00:00Z,300747,USA,USD,https://audio-ssl.itunes.apple.com/itunes-asse...,https://is1-ssl.mzstatic.com/image/thumb/Music...

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   track_id           4915 non-null   int64
 1   track_name         4915 non-null   object
 2   artist_name        4913 non-null   object
 3   collection_name    4915 non-null   object
 4   album_artist       1728 non-null   object
 5   genre              4915 non-null   object
 6   rating             4915 non-null   object
 7   track_price        4540 non-null   float64
 8   collection_price   4539 non-null   float64
 9   release_date       4867 non-null   object
 10  track_time_millis  4915 non-null   int64
 11  country            4915 non-null   object
 12  currency           4915 non-null   object
 13  preview_url        4914 non-null   object
 14  artwork_url        4915 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 576.1+ KB

In [ ]:
df2.describe()

           track_id  track_price  collection_price  track_time_millis
count  4.915000e+03  4540.000000       4539.000000       4.915000e+03
mean   1.363645e+09     1.197784          8.622703       2.395684e+05
std    4.250004e+08     0.238723          5.748893       1.206201e+05
min    6.920394e+06    -1.000000         -1.000000       3.050300e+04
25%    1.270556e+09     1.290000          4.990000       1.936015e+05
50%    1.445041e+09     1.290000          9.990000       2.266810e+05
75%    1.650842e+09     1.290000         10.990000       2.690320e+05
max    1.874863e+09     1.290000        119.990000       4.676058e+06

In [ ]:
print(f"Top 3 (head func)\n{df2.head(3)}")

Top 3 (head func)
     track_id                track_name                  artist_name  \
0  1624932774                      POP!                       NAYEON
1  1022164261                   Riptide                    Vance Joy
2  1207120448  Something Just Like This  The Chainsmokers & Coldplay

                          collection_name      album_artist        genre  \
0                               IM NAYEON               NaN        Dance
1  Dream Your Life Away (Special Edition)               NaN  Alternative
2                  Memories...Do Not Open  The Chainsmokers        Dance

  rating  track_price  collection_price          release_date  \
0  Clean         1.29              6.99  2022-06-24T12:00:00Z
1  Clean         1.29              9.99  2013-03-22T07:00:00Z
2  Clean         1.29              9.99  2017-02-22T08:00:00Z

   track_time_millis country currency  \
0             168107     USA      USD
1             202019     USA      USD
2             247165     USA      USD

                                         preview_url  \
0  https://audio-ssl.itunes.apple.com/itunes-asse...
1  https://audio-ssl.itunes.apple.com/itunes-asse...
2  https://audio-ssl.itunes.apple.com/itunes-asse...

                                         artwork_url
0  https://is1-ssl.mzstatic.com/image/thumb/Music...
1  https://is1-ssl.mzstatic.com/image/thumb/Music...
2  https://is1-ssl.mzstatic.com/image/thumb/Music...

In [ ]:
print(f"Last 3 (tail func)\n{df2.tail(3)}")

Last 3 (tail func)
        track_id                                   track_name  \
4912  1817490077  Khwabon Ko (Prem Geet / Soundtrack Version)
4913  1817490076      Suhani Sham Aayi Hai (From "Shaukeeen")
4914  1817507850           Mujhe Tadpati Rahi (From "Damaad")

                    artist_name          collection_name  \
4912              Suresh Wadkar  Old Hindi Songs - Vol.2
4913  Asha Bhosle & R.D. Burman  Old Hindi Songs - Vol.2
4914   Asha Bhosle & Mohd. Rafi  Old Hindi Songs - Vol.1

                     album_artist       genre rating  track_price  \
4912  Kishore Kumar & Asha Bhosle  Soundtrack  Clean          NaN
4913  Kishore Kumar & Asha Bhosle  Soundtrack  Clean          NaN
4914                Kishore Kumar  Soundtrack  Clean          NaN

      collection_price          release_date  track_time_millis country  \
4912               NaN  1981-01-01T12:00:00Z             232027     USA
4913               NaN  1982-01-01T12:00:00Z             283403     USA
4914               NaN  2007-05-07T12:00:00Z             300747     USA

     currency                                        preview_url  \
4912      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4913      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4914      USD  https://audio-ssl.itunes.apple.com/itunes-asse...

                                            artwork_url
4912  https://is1-ssl.mzstatic.com/image/thumb/Music...
4913  https://is1-ssl.mzstatic.com/image/thumb/Music...
4914  https://is1-ssl.mzstatic.com/image/thumb/Music...

In [ ]:
import numpy as np

In [ ]:
print(df2.isna().sum())

track_id                0
track_name              0
artist_name             2
collection_name         0
album_artist         3187
genre                   0
rating                  0
track_price           375
collection_price      376
release_date           48
track_time_millis       0
country                 0
currency                0
preview_url             1
artwork_url             0
dtype: int64

In [ ]:
#Insert
new_pd = pd.DataFrame({
    "track_name":["Attention"],
    "artist_name":["Charlie Puth"],
    "country": ["USA"]
})
with_new = pd.concat([df2, new_pd])
print(with_new)

          track_id                                         track_name  \
0     1.624933e+09                                               POP!
1     1.022164e+09                                            Riptide
2     1.207120e+09                           Something Just Like This
3     1.369380e+09                                             lovely
4     1.450696e+09                              when the party's over
...            ...                                                ...
4911  1.817490e+09  Dekh Lo Awaz Dekar (Prem Geet / Soundtrack Ver...
4912  1.817490e+09        Khwabon Ko (Prem Geet / Soundtrack Version)
4913  1.817490e+09            Suhani Sham Aayi Hai (From "Shaukeeen")
4914  1.817508e+09                 Mujhe Tadpati Rahi (From "Damaad")
0              NaN                                          Attention

                      artist_name                           collection_name  \
0                          NAYEON                                 IM NAYEON
1                       Vance Joy    Dream Your Life Away (Special Edition)
2     The Chainsmokers & Coldplay                    Memories...Do Not Open
3          Billie Eilish & Khalid                           lovely - Single
4                   Billie Eilish  WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?
...                           ...                                       ...
4911             Anuradha Paudwal                   Old Hindi Songs - Vol.2
4912                Suresh Wadkar                   Old Hindi Songs - Vol.2
4913    Asha Bhosle & R.D. Burman                   Old Hindi Songs - Vol.2
4914     Asha Bhosle & Mohd. Rafi                   Old Hindi Songs - Vol.1
0                    Charlie Puth                                       NaN

                     album_artist        genre rating  track_price  \
0                             NaN        Dance  Clean         1.29
1                             NaN  Alternative  Clean         1.29
2                The Chainsmokers        Dance  Clean         1.29
3                             NaN          Pop  Clean         1.29
4                             NaN  Alternative  Clean         1.29
...                           ...          ...    ...          ...
4911  Kishore Kumar & Asha Bhosle   Soundtrack  Clean          NaN
4912  Kishore Kumar & Asha Bhosle   Soundtrack  Clean          NaN
4913  Kishore Kumar & Asha Bhosle   Soundtrack  Clean          NaN
4914                Kishore Kumar   Soundtrack  Clean          NaN
0                             NaN          NaN    NaN          NaN

      collection_price          release_date  track_time_millis country  \
0                 6.99  2022-06-24T12:00:00Z           168107.0     USA
1                 9.99  2013-03-22T07:00:00Z           202019.0     USA
2                 9.99  2017-02-22T08:00:00Z           247165.0     USA
3                 1.29  2018-04-19T12:00:00Z           200187.0     USA
4                10.99  2018-10-17T07:00:00Z           196077.0     USA
...                ...                   ...                ...     ...
4911               NaN  1981-01-01T12:00:00Z           355067.0     USA
4912               NaN  1981-01-01T12:00:00Z           232027.0     USA
4913               NaN  1982-01-01T12:00:00Z           283403.0     USA
4914               NaN  2007-05-07T12:00:00Z           300747.0     USA
0                  NaN                   NaN                NaN     USA

     currency                                        preview_url  \
0         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
1         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
2         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
3         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
...       ...                                                ...
4911      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4912      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4913      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4914      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
0         NaN                                                NaN

                                            artwork_url
0     https://is1-ssl.mzstatic.com/image/thumb/Music...
1     https://is1-ssl.mzstatic.com/image/thumb/Music...
2     https://is1-ssl.mzstatic.com/image/thumb/Music...
3     https://is1-ssl.mzstatic.com/image/thumb/Music...
4     https://is1-ssl.mzstatic.com/image/thumb/Music...
...                                                 ...
4911  https://is1-ssl.mzstatic.com/image/thumb/Music...
4912  https://is1-ssl.mzstatic.com/image/thumb/Music...
4913  https://is1-ssl.mzstatic.com/image/thumb/Music...
4914  https://is1-ssl.mzstatic.com/image/thumb/Music...
0                                                   NaN

[4916 rows x 15 columns]

In [ ]:
index_diff = df1.index.difference(df2.index)
print(index_diff)

RangeIndex(start=4915, stop=5000, step=1)

In [ ]:
sym_diff = df1.index.symmetric_difference(df2.index)
print(sym_diff)

RangeIndex(start=4915, stop=5000, step=1)

In [ ]:
new_index = df1.index.union(df2.index)
print(new_index)

RangeIndex(start=0, stop=5000, step=1)

In [ ]:
dropped = df2.drop([4913,4914])
print(dropped)

        track_id                                         track_name  \
0     1624932774                                               POP!
1     1022164261                                            Riptide
2     1207120448                           Something Just Like This
3     1369380479                                             lovely
4     1450695872                              when the party's over
...          ...                                                ...
4908  1810515850                      Echoes Of Love Old Hindi Song
4909    30372391                                            Twisted
4910   712330693             I Got 5 On It (feat. Michael Marshall)
4911  1817490073  Dekh Lo Awaz Dekar (Prem Geet / Soundtrack Ver...
4912  1817490077        Khwabon Ko (Prem Geet / Soundtrack Version)

                      artist_name                           collection_name  \
0                          NAYEON                                 IM NAYEON
1                       Vance Joy    Dream Your Life Away (Special Edition)
2     The Chainsmokers & Coldplay                    Memories...Do Not Open
3          Billie Eilish & Khalid                           lovely - Single
4                   Billie Eilish  WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?
...                           ...                                       ...
4908                India Sangeet                           Old Hindi Songs
4909                  Keith Sweat                               Keith Sweat
4910                        Luniz                        Operation Stackola
4911             Anuradha Paudwal                   Old Hindi Songs - Vol.2
4912                Suresh Wadkar                   Old Hindi Songs - Vol.2

                     album_artist        genre rating  track_price  \
0                             NaN        Dance  Clean         1.29
1                             NaN  Alternative  Clean         1.29
2                The Chainsmokers        Dance  Clean         1.29
3                             NaN          Pop  Clean         1.29
4                             NaN  Alternative  Clean         1.29
...                           ...          ...    ...          ...
4908                          NaN    Worldwide  Clean         0.99
4909                          NaN     R&B/Soul  Clean         1.29
4910                          NaN  Hip-Hop/Rap  Clean         1.29
4911  Kishore Kumar & Asha Bhosle   Soundtrack  Clean          NaN
4912  Kishore Kumar & Asha Bhosle   Soundtrack  Clean          NaN

      collection_price          release_date  track_time_millis country  \
0                 6.99  2022-06-24T12:00:00Z             168107     USA
1                 9.99  2013-03-22T07:00:00Z             202019     USA
2                 9.99  2017-02-22T08:00:00Z             247165     USA
3                 1.29  2018-04-19T12:00:00Z             200187     USA
4                10.99  2018-10-17T07:00:00Z             196077     USA
...                ...                   ...                ...     ...
4908              9.99  2025-04-22T12:00:00Z             200342     USA
4909              9.99  1996-06-04T07:00:00Z             260667     USA
4910              7.99  1995-05-23T07:00:00Z             253533     USA
4911               NaN  1981-01-01T12:00:00Z             355067     USA
4912               NaN  1981-01-01T12:00:00Z             232027     USA

     currency                                        preview_url  \
0         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
1         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
2         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
3         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4         USD  https://audio-ssl.itunes.apple.com/itunes-asse...
...       ...                                                ...
4908      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4909      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4910      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4911      USD  https://audio-ssl.itunes.apple.com/itunes-asse...
4912      USD  https://audio-ssl.itunes.apple.com/itunes-asse...

                                            artwork_url
0     https://is1-ssl.mzstatic.com/image/thumb/Music...
1     https://is1-ssl.mzstatic.com/image/thumb/Music...
2     https://is1-ssl.mzstatic.com/image/thumb/Music...
3     https://is1-ssl.mzstatic.com/image/thumb/Music...
4     https://is1-ssl.mzstatic.com/image/thumb/Music...
...                                                 ...
4908  https://is1-ssl.mzstatic.com/image/thumb/Music...
4909  https://is1-ssl.mzstatic.com/image/thumb/Music...
4910  https://is1-ssl.mzstatic.com/image/thumb/Music...
4911  https://is1-ssl.mzstatic.com/image/thumb/Music...
4912  https://is1-ssl.mzstatic.com/image/thumb/Music...

[4913 rows x 15 columns]